JaiaToggle test:
jaiarobotics/jaiabot pull request #1013
Opened 2024-11-12 19:40 UTC by edsanville

JaiaToggle test:
* Tests toggling the value
* Tests disabling the widget

2024-11-13 18:42 UTC, edsanville commented on src/web/jcc/client/components/__tests__/JaiaToggle.test.tsx
> +        const toggle: HTMLInputElement = screen.getByRole("checkbox")
FYI:  getByTitle also worked.

2024-11-13 18:42 UTC, edsanville commented on .husky/_/pre-commit
> -exit 0
I have no idea!  That file seems to change every time I make a commit these days.  I think the `build.sh` script is changing it.

2024-11-19 15:21 UTC, ferrom-jaia requested changes
We need to resolve the pre-commit issue before merging

2024-11-19 15:21 UTC, ferrom-jaia commented on .husky/_/pre-commit
> -exit 0
I do not think we want this to be removed. @michael-jaia is the one who added it and I will defer to him. We should figure out why this is being overwritten.

2024-11-19 15:21 UTC, ferrom-jaia commented on src/web/jcc/client/components/__tests__/JaiaToggle.test.tsx
> +        var isChecked = false
Consider using let instead of var for isChecked to follow modern JavaScript best practices and ensuring block scoping.

2024-11-19 15:21 UTC, ferrom-jaia commented on src/web/jcc/client/components/__tests__/JaiaToggle.test.tsx
> +        var isChecked = false
Consider using let instead of var for isChecked to follow modern JavaScript best practices and ensuring block scoping.

2024-11-19 15:21 UTC, ferrom-jaia commented on src/web/jcc/client/components/__tests__/JaiaToggle.test.tsx
> +    test("JaiaToggle toggles", async () => {
Can the test name be JaiaToggle switching on/off?

2024-11-19 15:21 UTC, ferrom-jaia commented on src/web/jcc/client/components/__tests__/JaiaToggle.test.tsx
> +    test("JaiaToggle disables", async () => {
Does this need to be async?

2024-11-20 13:23 UTC, ferrom-jaia commented
The location of the test I think is in the wrong location as well. Take a look at the JaiaAbout component for an example of where we have been putting our tests.

2024-11-20 15:18 UTC, edsanville commented
> We need to resolve the pre-commit issue before merging

I'm reverting the changes that were made to this pre-commit file.  There's a script somewhere in the works that keeps making this change, but I haven't reproduced it yet.

2024-11-20 17:47 UTC, ferrom-jaia approved these changes
Looks great!

2024-11-20 19:08 UTC, merged