bug/JAIAB-189-fix-bugs-found-during-1-3-0-beta-testing
jaiarobotics/jaiabot pull request #318
Opened 2022-12-15 19:37 UTC by ferrom-jaia

Bugs:
Hub details undefined
Bot detail buttons do not work on predeployment failed
Shortcuts should not work while we type saving mission
Warning for max points
The shortcut for bot details does not save the accordian settings (open/close)
Multihold dive
PID depth

2022-12-15 21:10 UTC, jason-jaia requested changes
PID gains should always be positive. Dive code needs to be reviewed so this is true rather than changing the PIDControl message.

2022-12-15 21:27 UTC, jason-jaia requested changes, later dismissed
Maybe it would be a little clearer to say something like: "Adding this goal exceeds the limit of MAX_GOALS"

2022-12-15 21:36 UTC, jason-jaia commented on src/web/command_control/client/style/CommandControl.less
> +    color: black;
I wonder if this color should be a @button-text or something similar. Not sold on it, but want to make sure it's considered.

2022-12-19 15:05 UTC, michaelrockJAIA approved these changes
matt tested and approving to test on the hardware

2022-12-19 15:12 UTC, merged