feature/echo-driver
jaiarobotics/jaiabot pull request #765
Opened 2024-02-05 16:44 UTC by ferrom-jaia

# Summary
The echo driver will provide a way to communicate with the echo sensor (Turn on/off). The driver will query for the sensor's status every 1 second.
# Details
The approach for the echo driver is similar to the imu driver.
# Testing

1. Deploy code to a bot with a echo sensor
2. Start jaiabot services: ```sudo systemctl start jaiabot```
3. Make sure the hub is on and the services are running
4. Open jcc
5. Navigate to the JED
6. You will see a section for Echo Testing
7. Options available: Start and Stop
8. After each start or stop command sent you will need to query for a new status
9. When the echo sensor has been started it will be in the RUNNING state
10. When the echo sensor has been stopped it will be in the READY state

Another test:
1. With everything still running stop the python echo driver ```sudo systemctl stop jaiabot_echo_py.service```
2. After 20 seconds the driver should restart
3. Go through starting and stopping the echo sensor again

2024-02-20 23:19 UTC, michael-twomey reviewed
Code is digestible and easy to follow. I left some comments (nothing major). One general thing we need to add is function comments (expect JED since we have not set that standard).

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/drivers/echo/app.cpp
> +        // Deserialize from the UDP packet
Set D to lowercase

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/drivers/echo/app.cpp
> +            glog.is_warn() && glog << "Couldn't deserialize EchoData from the UDP packet" << endl;
Do you like EchoData or Echo data (just looking here and line 102)

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/drivers/echo/app.cpp
> +            // Publish only when we get a query for status
Set P to lowercase

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/drivers/echo/app.cpp
> +    // Just send an empty packet
I think we want to start comments with a lowercase letter. Lmk if you wanna go a different direction

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/drivers/echo/app.cpp
> +        glog.is_warn() && glog << "Timeout on echo" << std::endl;
Not sure if you want to capitalize the e in echo for consistency

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/drivers/echo/config.proto
> +    optional jaiabot.protobuf.EchoIssue.SolutionType echo_issue_solution = 12 [default = REBOOT_ECHO_IMU_AND_RESTART_ECHO_PY];
Adjust wording of warning message

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/health/app.cpp
> +                    glog.is_debug2() && glog << "ECHO ERROR: RESTART ECHO PY. " << std::endl;
Do you also want to say that it is rebooting the Echo board?

2024-02-20 23:19 UTC, michael-jaia commented on src/bin/health/app.cpp
> +                default:
Is there ever going to be a default?

2024-02-20 23:19 UTC, michael-jaia commented on src/lib/messages/echo.proto
> +enum EchoState
Should we put the EchoState enum inside the EchoData message to stay consistent with the format of the other messages?

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +                log.debug('Connected, Done with setup, Get Status')
Keep cases consistent in debug statements

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +        """
Add the end quotes to the end of the line

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +                cc=str(self.sensor.readline().decode('utf-8').strip())
What does cc stand for? + Let's add an spaces before and after the equal sign

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +                        state = int(state)
Should we move line 118 into line 120?

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +    def getStatus(self):
Is there a reason for using both status and state? Aren't they the same?

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +            while True:
What is going to break this while loop? Once the sensor is turned off cc will no longer start with $ECHO?

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/echo.py
> +    def stopDevice(self):
Why can't we stop the echo board in the ready state?

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/jaiabot_echo.py
> +parser.add_argument('port', metavar='port', type=int, help='port to publish echo data')
Should the e in echo be capitalized?

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/jaiabot_echo.py
> +
Remove blank line

2024-02-20 23:19 UTC, michael-jaia commented on src/python/echo/jaiabot_echo.py
> +        data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
Bump comment up and capitalize B

2024-02-20 23:19 UTC, michael-twomey commented on src/web/jed/echo.js
> +        const selected_bot_id = botDropdown.getSelectedBotId()
Switch to camelCase

2024-02-20 23:19 UTC, michael-twomey commented on src/web/jed/echo.js
> +        if (thisBot == null)  return
Could be !== undefined

2024-02-20 23:19 UTC, michael-twomey commented on src/web/jed/echo.js
> +        if (engineering_status.echo.echo_state == null) return
I think we just need this line with a !== undefined (but it will need to be tested in a sandbox)

2024-02-20 23:19 UTC, michael-twomey commented on src/web/jed/echo.js
> +            // Return early if initCheck failed
I don't think we need this check since the code tells the story pretty clearly here

2024-02-20 23:19 UTC, michael-twomey commented on src/web/jed/echo.js
> +            // Return early if initCheck failed
Same as previous comment

2024-02-20 23:19 UTC, michael-twomey commented on src/web/jed/echo.js
> +            // Return early if initCheck failed
Same as previous comment

2024-02-21 14:20 UTC, michael-twomey requested changes
Adding the "Request changes" tag to my review

2024-02-22 16:52 UTC, michael-twomey commented on src/python/echo/echo.py
> +    def stopDevice(self):
Add comment here

2024-02-22 17:47 UTC, michael-twomey commented
## Approving Review
Approving this pull request knowing there are outstanding changes requested. As the person who requested these changes I know they fall into the category of code cleanup over functionality/bug fixes. Given this and the business requirements, I am going to approve and merge this pull request into 1.y so we can move forward with the on the water testing and ship the bots. Subsequent tickets will be created for the next sprint to resolve the requested changes.

2024-02-22 17:48 UTC, michael-twomey approved these changes

2024-02-22 17:56 UTC, merged