Task/refactor state machine to create pause state
jaiarobotics/jaiabot pull request #766
Opened 2024-02-06 01:15 UTC by tsaubergine

2024-02-12 17:02 UTC, michael-twomey requested changes
I think this feature will be a nice option for operators. While playing with it in sim, I came across the following bug:
1. Create a run (assign a bot to it)
2. Play the run
3. After the run completes and the bot is station keeping, if you click the play all button, the bot will remain in a station keeping state (as opposed to restarting the run)

2024-02-12 23:20 UTC, ferrom-jaia commented
> I think this feature will be a nice option for operators. @ferrom-jaia While playing with it in sim, I came across the following bug:
> 
> 1. Create a run (assign a bot to it)
> 2. Play the run
> 3. After the run completes and the bot is station keeping, if you click the play all button, the bot will remain in a station keeping state (as opposed to restarting the run)

This bug was already in 1.y. I have added a pull request to fix the issue. The described issue needs to have an unassigned run to reproduce error: https://github.com/jaiarobotics/jaiabot/pull/778

2024-02-12 23:34 UTC, tsaubergine commented
@ferrom-jaia The Play button (which is now Pause) is useful for re-playing the mission once you reach the end. I would suggest switching it back to Play at the end of the mission (perhaps at IN_MISSION::UNDERWAY::RECOVERY).

2024-02-13 01:00 UTC, ferrom-jaia commented
> @ferrom-jaia The Play button (which is now Pause) is useful for re-playing the mission once you reach the end. I would suggest switching it back to Play at the end of the mission (perhaps at IN_MISSION::UNDERWAY::RECOVERY).

Great idea! I will add that.

2024-02-13 19:12 UTC, michael-twomey requested changes
@ferrom-jaia Leaving GitHub inline comments

2024-02-13 19:12 UTC, michael-jaia commented on src/web/command_control/client/components/CommandControl.tsx
> +		if (botInfo.botIdsPauesNotAvaiable.length !==0) {
Let's add a space after the last equal sign

2024-02-13 19:12 UTC, michael-jaia commented on src/web/command_control/client/components/CommandControl.tsx
> +						let c = {
Can we call the c variable command. I know in other parts of the code its named c but those should really be command. We can start the change by renaming this one command.

2024-02-13 19:12 UTC, michael-jaia commented on src/web/command_control/client/components/CommandControl.tsx
> +						console.log(c)
Similar thing here, we have console.log statements in other places but we probably shouldn't for production code. Do you agree?

2024-02-13 19:12 UTC, michael-jaia commented on src/web/command_control/client/components/CommandControl.tsx
> +	 * @param sendingPause determines output and bot bots to send the pause command to
I think we only need bots here (I guess it's contagious as it comes from other the untouched code above haha)

2024-02-13 19:12 UTC, michael-twomey commented on src/web/command_control/client/components/CommandControl.tsx
> +			} else if (sendingPause && (!stopAvailable.test(bot?.mission_state) ||
I am pretty confused by this else if block. Maybe it needs a comment or just a quick explanation in reply to this msg

2024-02-13 19:12 UTC, michael-twomey commented on src/web/command_control/client/components/CommandControl.tsx
> +			botInfo.pauesNotAvaiableMessage  = `\nThe command cannot be sent to Bot${botInfo.botIdsPauesNotAvaiable.length > 1 ? 's': ''}: ` + botInfo.botIdsPauesNotAvaiable + ` because ${botInfo.botIdsPauesN
I think this is where we need to make it 'they are' and 'it is'

2024-02-13 19:12 UTC, michael-twomey commented on src/web/command_control/client/components/CommandControl.tsx
> +						let c = {
Wondering if we can do the same thing as above and name this variable command

2024-02-13 19:12 UTC, michael-twomey commented on src/web/command_control/client/components/Details.tsx
> +        statesAvailable: [
Should we add statesNotAvailable for consistency with the pause button, or do we even need that property for these btns?

2024-02-13 20:14 UTC, ferrom-jaia approved these changes
Looks great! Tested in sim with the procedures outlined in the pull request description (Super helpful!).

2024-02-14 15:55 UTC, michael-twomey approved these changes, later dismissed
Tested web-side: The pause feature worked smoothly in sim. I focused on pausing individual bots, resuming individual bots, and the workings of the pause feature when a mission completes. Then I mixed in testing with the play all, pause-all and how it works when some bots are paused, moving, or stopped. The bots entered all of the expected states for the commands sent.

2024-02-14 21:11 UTC, ferrom-jaia requested changes
Need to do on the water testing before merging into 1.y

2024-02-24 17:00 UTC, ferrom-jaia submitted a review, later dismissed
Removed UI code until we agree on a way forward. Backend works as expected.

2024-02-24 17:06 UTC, ferrom-jaia approved these changes

2024-02-24 17:13 UTC, merged