feature/download panel
jaiarobotics/jaiabot pull request #801
Opened 2024-02-22 18:20 UTC by Moriarty777

**Made some changes to the UI.** 
- The download Queue button has now been replaced with Download Panel Button. 
- It also contains Download all button which has been moved to the Download Panel.
- Download Panel also has 2 accordions. One contains Download KMZ & CSV buttons. The other one is Download Queue.
- Download KMZ & CSV buttons have been removed from Settings Panel.
- Download Queue file has been deleted since its code is being directly used in Download Panel.
- Help Window has also been updated to reflect the changes.

![Screenshot from 2024-02-20 13-29-59](https://github.com/jaiarobotics/jaiabot/assets/54315064/c92a167e-98d0-4ab7-a131-945851a45bc3)

2024-02-23 18:31 UTC, ferrom-jaia requested changes
Looks good Eric. I left a couple of comments and suggestions. When you get a chance can you review and resolve items I pointed out.

Not sure if I like the no spaces between the bots in the download queue. 

Before changes:
![image](https://github.com/jaiarobotics/jaiabot/assets/109534520/e048acab-11c0-4702-bd7a-3a1ad043bcc6)

After changes: 
![image](https://github.com/jaiarobotics/jaiabot/assets/109534520/f60df078-3d9a-4f6d-a9dc-1894418a23d5)

What do you think?

2024-02-23 18:31 UTC, ferrom-jaia commented on src/web/command_control/client/components/DownloadPanel.tsx
> +     *
Missing return type:
https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page110_coding_standards.md

2024-02-23 18:31 UTC, ferrom-jaia commented on src/web/command_control/client/components/DownloadPanel.tsx
> +			</Button>
Spacing seems off here

2024-02-23 18:31 UTC, ferrom-jaia commented on src/web/command_control/client/components/DownloadPanel.tsx
> +    const handleDownloadAll = async () => {
Function comment mission: https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page110_coding_standards.md

2024-02-23 18:31 UTC, ferrom-jaia commented on src/web/command_control/client/components/DownloadPanel.tsx
> +    const handleAccordionTabClick = (accordionTab: AccordionTabs) => {
Function comment mission: https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page110_coding_standards.md

2024-02-23 18:31 UTC, ferrom-jaia commented on src/web/command_control/client/components/DownloadPanel.tsx
> +    const isOpenAccordionTab = (accordionTab: AccordionTabs) => {
Function comment mission: https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page110_coding_standards.md

2024-02-27 16:01 UTC, michael-twomey reviewed
Hey Eric just curious to your thinking behind removing this file. Did you consider importing this component into DownloadPanel.tsx?

2024-02-27 16:17 UTC, Moriarty777 commented
> Hey Eric just curious to your thinking behind removing this file. Did you consider importing this component into DownloadPanel.tsx?

1. So my first thought was having all the DownloadPanel component related codes to be in the same file. That way debugging and adding new features in the future will be easy.
2.  I ran into some issues trying to integrate the DownloadQueue component into Download Panel component. The code structure didn't quite align with the accordion layout, so I had to make some adjustments to fit it in smoothly. In the end i thought rather than keep changing the download queue file i could directly integrate it into my component and make necessary changes as needed.

2024-02-28 14:03 UTC, ferrom-jaia approved these changes
Looks great!

2024-02-28 14:03 UTC, merged