task/create-script-to-detect-bots-not-moving-in-transit
jaiarobotics/jaiabot pull request #805
Opened 2024-02-27 16:24 UTC by marshalllele

Scripts to find false dives and false transits from data.h5 files.

2024-02-27 16:27 UTC, marshalllele commented
Need to update to track and display the variables we think may be responsible for false dives/transits.
Ideas:
* Temp.
* Battery percentage

2024-02-28 17:03 UTC, michael-twomey requested changes
![image](https://github.com/jaiarobotics/jaiabot/assets/109538793/2dbc24fb-b05d-41d7-b982-943c66eb74d1)
Hey Nick, I ran into this error when running the script. Lmk if you are expecting it to be ran a different way

2024-03-01 20:38 UTC, michael-jaia submitted a review, later dismissed
Review for false_dive.py

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +
Remove space

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +def main():
I think we should remove the Args section from the docstring since we are not passing in an arg to the main function

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +    Args:
For the descriptions with the arguments, we really just want to say why they are being passed. I think you do a good job of that for the first three args with the sentences that start with Used... and for bot_id starting with Helps... I think you should cut the sentences that start with List... and the words before "help" and turn that into "Helps

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +
Remove line

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +    """ Tests two different utimes to ensure they aren't within the same second.
Remove space in front of Tests...

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +    """ Prints the collected data.
Remove space in front of Prints...

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +    return utime_to_realtime(round(utime_1 / 1_000_000)) == utime_to_realtime(round(utime_2 / 1_000_000))
Can we create a variable for 1_000_000 so the next person to read this code can quicky figure out what it represents

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +        dt (date/time): Converted and readable time.
For the return docstrings we want to use the format 
```
Returns:
    type: Description.
```

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +    """ Opens each .h5 file withint the given directory, handles the data, and locates any false dives within the file.
Remove "t"

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +
Remove blank line to keep the return statement tight to its containing if block

2024-03-13 18:13 UTC, michael-jaia commented on scripts/log-analysis/false_dive.py
> +                false_indices = []
Do these variables (dive_indices and false_indices) need to be arrays or could they just be counter variables?

2024-03-13 18:13 UTC, michael-twomey commented on scripts/log-analysis/false_dive.py
> +                taskPacket = file['jaiabot::task_packet;0/jaiabot.protobuf.TaskPacket']
Let's use snake case for consistency here

2024-03-21 13:35 UTC, ferrom-jaia commented on scripts/log-analysis/false_transit.py
> +#!/usr/bin/env python3
Can we update this script for how the bot is detecting false transits: 

// To determine no forward progress:
//    If the vehicle is in the vertical position; pitch > resolve_pitch_threshold  (default 30 deg)
//    If the vehicle desired speed is > resolve_desired_speed_threshold (default: 0 m/s)
//    How long to give the vehicle to get to the horizontal position: resolve_no_forward_progress_timeout (default: 15 sec)

2024-04-09 21:25 UTC, ferrom-jaia approved these changes
Looks good! Tested on my machine.

2024-04-09 21:26 UTC, merged