Feature/add angular output for imu
jaiarobotics/jaiabot pull request #825
Opened 2024-03-28 03:01 UTC by edsanville

2024-03-30 16:03 UTC, edsanville commented
> Tested on b3f1, and gives quaternion and angular_velocity data in interactive mode.
> 
> When run with systemctl, however, I get these errors: `Mar 28 03:17:14 bot3-fleet1 python3[12342]: 2024-03-28 03:17:14,285 WARNING Error trying to get data: 0 Mar 28 03:17:14 bot3-fleet1 python3[12342]: 2024-03-28 03:17:14,285 WARNING getIMUData returned None Mar 28 03:17:14 bot3-fleet1 python3[12342]: 2024-03-28 03:17:14,374 WARNING Error trying to get data: ('Unprocessable Batch bytes', 1) Mar 28 03:17:14 bot3-fleet1 python3[12342]: 2024-03-28 03:17:14,375 WARNING getIMUData returned None Mar 28 03:17:34 bot3-fleet1 python3[12342]: 2024-03-28 03:17:34,184 WARNING Error trying to get data: 0 Mar 28 03:17:34 bot3-fleet1 python3[12342]: 2024-03-28 03:17:34,184 WARNING getIMUData returned None Mar 28 03:17:34 bot3-fleet1 python3[12342]: 2024-03-28 03:17:34,389 WARNING Error trying to get data: 0 Mar 28 03:17:34 bot3-fleet1 python3[12342]: 2024-03-28 03:17:34,389 WARNING getIMUData returned None Mar 28 03:17:34 bot3-fleet1 python3[12342]: 2024-03-28 03:17:34,474 WARNING Error trying to get data: ('Unprocessable Batch bytes', 1) Mar 28 03:17:34 bot3-fleet1 python3[12342]: 2024-03-28 03:17:34,475 WARNING getIMUData returned None `
> 
> Not sure what they are yet...

Looks like these are from the system resetting the GPIO pins, because the test bot doesn't have an Echo device installed.  The solution for echo problems is set to reset the echo (GPIO pins), and reset the echo driver script.  So, this issue doesn't have anything to do with the IMU software directly.

Here's the reported quaternion and angular velocity vector in liaison:
![image](https://github.com/jaiarobotics/jaiabot/assets/19232537/2beacd71-10a4-4152-98a4-4f7f504366f5)

2024-04-08 14:40 UTC, ferrom-jaia requested changes

2024-04-08 14:40 UTC, ferrom-jaia commented on .docker/focal/amd64/Dockerfile
> +RUN echo -e "deb http://packages.jaia.tech/ubuntu/continuous/1.y/ ${distro}/\ndeb http://packages.jaia.tech/ubuntu/gobysoft/continuous/1.y/ ${distro}/" >> /etc/apt/sources.list.d/jaiabot_release_1.y.
Can we remove this from the pull request

2024-04-08 14:40 UTC, ferrom-jaia commented on .docker/focal/arm64/Dockerfile
> +RUN echo -e "deb http://packages.jaia.tech/ubuntu/continuous/1.y/ ${distro}/\ndeb http://packages.jaia.tech/ubuntu/gobysoft/continuous/1.y/ ${distro}/" >> /etc/apt/sources.list.d/jaiabot_release_1.y.
Can we remove this from the pull request

2024-04-08 14:40 UTC, ferrom-jaia commented on config/gen/systemd.py
> +        'args': '-d bno085 -p 20000',
Can we use the enum set in this file to set the bno085 value?

2024-04-08 14:40 UTC, ferrom-jaia commented on config/gen/systemd.py
> +        'args': '-d bno055 -p 20000',
Can we use the enum set in this file to set the bno085 value?

2024-04-08 14:40 UTC, ferrom-jaia commented on src/lib/messages/imu.proto
> +
Can we add imu device type here? It may be useful to know if we are using bno085 and bno055

2024-04-08 14:40 UTC, ferrom-jaia commented on src/python/adafruit/imu.py
Can we separate bno085 into its own file? And then import it into this one.

2024-04-08 14:40 UTC, ferrom-jaia commented on src/python/adafruit/imu.py
> +class AdafruitBNO055(IMU):
Can we separate bno055 into its own file? And then import it into this one.

2024-04-08 14:40 UTC, ferrom-jaia commented on src/python/adafruit/jaiabot_imu.py
>          imu = Adafruit()
This should be AdafruitBNO085

2024-04-11 12:53 UTC, ferrom-jaia requested changes

2024-04-11 12:53 UTC, ferrom-jaia commented on src/doc/markdown/page80_timing.md
> +| jaiabot_adafruit_BNO055_py             | adafruit_BNO055 Sensor Updates                                                  | Depends jaiabot_adafruit_BNO055 | src/python/adafruit/jaiabot_imu.py
Can we add the 085 to this list

2024-04-11 12:53 UTC, ferrom-jaia commented on src/doc/markdown/page82_timing_health_updates.md
> +| jaiabot_adafruit_BNO055                 | Missing Data Detection                                                         | 40            | src/python/adafruit/jaiabot_imu.py                  | 2022
Can we add the 085 to this list

2024-04-30 13:31 UTC, michael-jaia approved these changes
Approving PR, tested on a bot with the BNO055 and BNO085 IMU and saw the angular velocity and quaternion data update in Liaison.

2024-04-30 15:54 UTC, ferrom-jaia approved these changes

2024-04-30 15:55 UTC, merged