feature/station-keep-for-a-certain-time
jaiarobotics/jaiabot pull request #860
Opened 2024-05-10 19:49 UTC by marshalllele

2024-05-23 18:30 UTC, michael-jaia requested changes
Hey Nick, I saw in your description that you do not want the last wpt to allow a station keep time to be set. I noticed a single wpt run allows a time to be added for station keep. Is that the behavior you want or should a single wpt run no allow an operator to set a time?

2024-05-23 18:30 UTC, michael-jaia commented on src/web/jcc/client/components/TaskSettingsPanel.tsx
> +    function onChangeStationKeepParameter(evt: React.ChangeEvent<HTMLInputElement>) {
Hey Nick, can you add a function comment here and switch the `var` to `let`. I know all the other related functions use `var` but lets stop that trend.

2024-05-24 16:18 UTC, ferrom-jaia commented
> Hey Nick, I saw in your description that you do not want the last wpt to allow a station keep time to be set. I noticed a single wpt run allows a time to be added for station keep. Is that the behavior you want or should a single wpt run no allow an operator to set a time?

It is okay if the user sets the last wpt as a station keep task with a duration. The vehicle will go into recovery state and will station keep at the last wpt.

2024-05-24 16:22 UTC, michael-jaia submitted a review, later dismissed
Statically reviewed code + tested in simulator with single waypoint mission, survey mission, and a classic run. When testing on the classic run (4 wpts), I added multiple station keep tasks to make sure the time set on one waypoint did not overwrite the time saved on another.

2024-05-28 13:29 UTC, ferrom-jaia approved these changes
Looks good! Tested in sim.

2024-05-28 13:37 UTC, merged