jaia-497-bug/race-condition-fleet2-radio
jaiarobotics/jaiabot pull request #895
Opened 2024-06-07 21:15 UTC by ferrom-jaia

2024-06-10 16:41 UTC, michael-jaia requested changes

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.cpp
> +    // Start trying to enter command mode
I think the function name is descriptive enough where we do not need the comment

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.cpp
> +    //Triggers menu to appear for bypass
Nit: Add space between // and Triggers

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.h
> +    //convert string to hex
Nit: Match with other comment format

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.cpp
> +        if (!ec)
Is it possible that asyc_wait produces an error code. If so would the try_enter_command_mode handle indefinitely?

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.cpp
> + * @brief Function to convert the string to hexadecimal format and return as a string
Nit: "return as a string "may not be necessary here. It may be more concise to say "...to a hexadecimal formatted string" if you want to include the word "string" in the brief.

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.h
General: What is the format the docstring comments should follow. Some have return statements some do not.

2024-06-10 16:41 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.cpp
>  void jaiabot::comms::XBeeDevice::enter_command_mode()
Do we need `enter_command_mode` to wrap `try_enter_command_mode`? Could we either call `try_enter_command_mode` directly or rename `try_enter_command_mode` to `enter_command_mode`

2024-07-29 21:42 UTC, ferrom-jaia commented on src/lib/comms/xbee/xbee.h
Hmm, do you think we should be consistent and add return void?

2024-07-31 18:26 UTC, michael-jaia commented on src/lib/comms/xbee/xbee.cpp
> +        if (!ec)
No, if async_wait produces an error code, it will be handled in the else statement of lambda passed to async_read_with_timeout

2024-08-01 18:38 UTC, michael-jaia approved these changes
Code tested on Fleet 0, Bot 1 (XBee 250MW) and Fleet 1, Bot 1 (XBee 900MW).

![xbee-900](https://github.com/user-attachments/assets/926ccfb6-83ae-438e-8ef9-d101d75b6c5f)
![xbee-250](https://github.com/user-attachments/assets/63410dc2-0795-4f60-b47b-424f93ce9f03)

2024-08-01 18:40 UTC, merged