Use a color map for depth contours
jaiarobotics/jaiabot pull request #928
Opened 2024-07-15 23:03 UTC by edsanville

Use Polygon objects with fill colors in the GeoJSON returned by the contour endpoints.

2024-07-15 23:14 UTC, edsanville commented
Whoops... forgot to document a few functions there!

2024-07-19 22:05 UTC, edsanville commented
Ok, function comments in place!

2024-07-23 17:09 UTC, edsanville commented on src/python/pyjaia/pyjaia/contours.py
> +        dive0.lat + fraction * (dive1.lat - dive0.lat)
Oh wow, good point!

2024-07-24 19:23 UTC, ferrom-jaia requested changes
Before approving can we make the contour map non selectable. I can see an operator getting confused by this.

2024-07-24 23:38 UTC, edsanville commented
It turns out that the Translate interaction (for dragging Rally Points?) filtered by the `disableDrag` property, which made draggability opt-out in JCC.  

So, it turns out every feature was draggable, but we didn't notice because most features are being updated by the status polling!  It turns out the Rally Points were opting out anyway, so they were the only feature that were NOT draggable.

I converted it to `enableDrag` to make draggability opt-IN, instead.  If we want to make features draggable, we can enable this property, and work on the hooks for the Translate interaction to do the actual work of re-positioning stuff.

2024-07-26 21:05 UTC, ferrom-jaia approved these changes
Looks great! Tested in sim.

2024-07-26 21:19 UTC, merged