Feature/rc speed override/jaia 1258
jaiarobotics/jaiabot pull request #929
Opened 2024-07-17 15:36 UTC by JRoybot

Added a toggle to enable "Overdrive" which results in a max speed of 3 (60%).  User is asked to confirm the use of Overdrive before it is enabled.

2024-07-20 00:07 UTC, edsanville reviewed
Looks good with comments, seems to work!

2024-07-20 00:07 UTC, edsanville commented on src/web/jcc/client/components/RCControllerPanel.tsx
> +type bin = { binNumber: number; binValue: number };
I would suggest capitalizing the type to `Bin`.  I believe the app uses an informal convention of capitalized types, and lowercase variable names.  At least, that's what I've been using.

2024-07-20 00:07 UTC, edsanville commented on src/web/jcc/client/components/RCControllerPanel.tsx
> +        this.state.overdriveEnabled = !this.state.overdriveEnabled;
Need to use the setState method here:
`this.setState({overdriveEnabled: !this.state.overdriveEnabled});`

2024-07-20 00:07 UTC, edsanville commented on src/web/jcc/client/components/RCControllerPanel.tsx
> +        console.log("overdriveEnabled set to %s", this.state.overdriveEnabled?"true":"flase")
Remove or change to `console.info()` or `console.debug()`?

2024-07-22 17:22 UTC, ferrom-jaia requested changes
Looks good! Just a few things to add.

2024-07-22 17:22 UTC, ferrom-jaia commented on src/web/jcc/client/components/RCControllerPanel.tsx
>      updateThrottleDirectionMove(event: IJoystickUpdateEvent) {
We should add a comment for this function since it was changed in this pull request.

2024-07-22 17:22 UTC, ferrom-jaia commented on src/web/jcc/client/components/RCControllerPanel.tsx
> +
remove space

2024-07-22 17:22 UTC, ferrom-jaia commented on src/web/jcc/client/components/RCControllerPanel.tsx
> +
remove space

2024-07-22 17:22 UTC, ferrom-jaia commented on src/web/jcc/client/components/RCControllerPanel.tsx
>      updateRudderDirectionMove(event: IJoystickUpdateEvent) {
We should add a comment for this function since it was changed in this pull request.

2024-07-22 17:22 UTC, ferrom-jaia commented on src/web/jcc/client/components/RCControllerPanel.tsx
>      calcRudderBinNum(
We should add a comment for this function since it was changed in this pull request.

2024-07-23 17:07 UTC, edsanville approved these changes, later dismissed

2024-07-24 19:42 UTC, ferrom-jaia approved these changes
Looks good! I updated the function comments. I went off this document: https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page110_coding_standards.md

2024-07-24 19:49 UTC, merged