Task/add task packets to rest api jaia 1517
jaiarobotics/jaiabot pull request #939
Opened 2024-07-29 12:23 UTC by edsanville

Implemented the task packet API endpoint.

2024-07-29 14:24 UTC, tsaubergine commented
I changed the base branch to https://github.com/jaiarobotics/jaiabot/tree/feature/app-for-api/jaia-1460 to simplify review of this PR (as it builds on that work).

2024-07-29 14:51 UTC, tsaubergine requested changes
Please add filtering by jaia_request.target - Right now I always get all the task packets, whereas if I send, for example:

`http://localhost:9092/jaia/v1/task_packets/b1?start_date=1722177986720894&end_date=1722350786720894`

I just want task packets from bot 1

2024-07-29 14:51 UTC, tsaubergine commented on src/web/rest_api/common/time.py
> +def iso_date_microseconds(iso_date: str):
Do we still need this now that we're using the UNIX microseconds? If not I'd suggest removing (I want to keep the lines of code count in the REST API as low as possible)

2024-07-29 14:51 UTC, tsaubergine commented on src/lib/messages/rest_api.proto
> +    required uint64 start_date = 1 [(jaia.field).rest_api.presence = GUARANTEED];
I'd prefer "start_time" and "end_time" for a unix timestamp field.

2024-08-02 16:27 UTC, edsanville commented
> Please add filtering by `jaia_request.target` - Right now I always get all the task packets, whereas if I send, for example:
> 
> `http://localhost:9092/jaia/v1/task_packets/b1?start_date=1722177986720894&end_date=1722350786720894`
> 
> I just want task packets from bot 1

Whoops, yes this was an oversight.

2024-08-05 18:01 UTC, merged

2024-08-05 18:01 UTC, tsaubergine commented
Merging into https://github.com/jaiarobotics/jaiabot/pull/925; final review can happen there.